### ISSUE TITLE
Lemonade breaks on Rails3

### ISSUE THREAD

**Issue by pfeiffer** [hagenburger/lemonade#4]
Lemonade (both master and gem) breaks on Rails 3:

```
[...]/gems/haml-3.0.6/lib/haml/util.rb:267:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)
from [...]/gems/haml-3.0.6/lib/sass/plugin/rails.rb:5:in `<top (required)>'
from [...]/gems/haml-3.0.6/lib/sass/plugin.rb:268:in `require'
from [...]/gems/haml-3.0.6/lib/sass/plugin.rb:268:in `<top (required)>'
from [...]/gems/lemonade-0.2.0/lib/lemonade.rb:10:in `require'
from [...]/gems/lemonade-0.2.0/lib/lemonade.rb:10:in `<top (required)>'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:46:in `require'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:46:in `block (2 levels) in require'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:41:in `each'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:41:in `block in require'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:40:in `each'
from [...]/gems/bundler-0.9.25/lib/bundler/runtime.rb:40:in `require'
from [...]/gems/bundler-0.9.25/lib/bundler.rb:89:in `gem_require'
from [..]/config/application.rb:7:in `<top (required)>'
from [...]/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/railties/lib/rails/commands.rb:28:in `require'
from [...]/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/railties/lib/rails/commands.rb:28:in `block in <top (required)>'
from [...]/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/railties/lib/rails/commands.rb:27:in `tap'
from [...]/bundler/gems/rails-16a5e918a06649ffac24fd5873b875daf66212ad-master/railties/lib/rails/commands.rb:27:in `<top (required)>'
from script/rails:9:in `require'
from script/rails:9:in `<main>'
```

Might have to do with Rails3 new lazy loading. See for instance http://github.com/chriseppstein/compass/issues/issue/137

**Comment by hagenburger** [comment]
Still working on it.

**Comment by hagenburger** [comment]
Now it works for me with Rails beta 4 and:
gem 'compass',     '0.10.2'
gem 'haml-edge',   '3.1.49', :require => 'haml'
